output "cluster_endpoint" {
  description = "Endpoint for GKE control plane."
  sensitive   = true
  value       = data.google_container_cluster.gke.endpoint
}

output "kubeconfig" {
  description = "kubectl config as generated by the module."
  sensitive   = true
  value       = module.gke_auth.kubeconfig_raw
}

output "region" {
  description = "GCP region."
  value       = var.region
}

output "cluster_id" {
  value = var.cluster_id
}

output "cluster_name" {
  value = var.cluster_name
}

output "cluster_name_short" {
  value = local.cluster_name_short
}

output "cluster_domain_name_servers" {
  value = module.dns.name_servers
}

